# "off" or 0 - turn the rule off
# "warn" or 1 - turn the rule on as a warning (doesn’t affect exit code)
# "error" or 2 - turn the rule on as an error (exit code is 1 when triggered)

extends:
  airbnb
rules:
  class-methods-use-this: warn
  react/prefer-stateless-function: off
  react/jsx-filename-extension: off
  import/newline-after-import:
    - error
    - count: 2
  import/order:
    - error
    - newlines-between: always-and-inside-groups
